# Generated by Django 5.2.3 on 2025-06-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_landing_url_employee_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL'),
        ),
    ]
